version: '3'

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../notification_system:/usr/src/app
    ports:
      - "8000:8000"
    container_name: notification_system_web
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug

    depends_on:
      - pgdb  #PostgreSQL server starts before the web service
    env_file:
      - ../notification_system/.env

  pgdb:
    image: postgres
    container_name: notification_system_db
    volumes:
      - notification_data:/var/lib/postgresql/data
    env_file:
      - ../notification_system/.env


volumes:
  notification_data: